services:
  flagd:
    image: ghcr.io/open-feature/flagd:latest
    volumes:
      - ./flags:/flags
    command: [
      'start',
      '--uri',
      'file:./flags/demo.flagd.json',
    ]
    ports:
      - '8013:8013'